### ISSUE TITLE
null Token causes NPE

### ISSUE THREAD

**Issue by roryodonnell** [IBM/ibm-cos-sdk-java#10]
tokenExpiresInSecs = Integer.parseInt(token.getExpires_in());
```
ERROR [2018-05-11 08:21:17,497] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 29b2039092d5264c
! java.lang.NullPointerException: null
! at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.cacheToken(DefaultTokenManager.java:246)
! at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.retrieveToken(DefaultTokenManager.java:375)
! at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.getToken(DefaultTokenManager.java:190)
! at com.ibm.cloud.objectstorage.oauth.IBMOAuthSigner.sign(IBMOAuthSigner.java:40)
! at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1164)
! at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
! at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
! at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
! at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
! at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
! at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
```

**Comment by smcgrath-IBM** [comment]
Hi @roryodonnell we'll look into this. It should be handled better. Were you running normal IAM authentication flow or have you written any custom token provider implementation?

**Comment by smcgrath-IBM** [comment]
Looks like it is failing to retrieve a token, although it should handle the null object better. Can you reach https://iam.ng.bluemix.net/oidc/token from within minikube?

**Comment by roryodonnell** [comment]
haven't tried that

**Comment by smcgrath-IBM** [comment]
@roryodonnell did you get connectivity within minikube to the token endpoint? If so, did it resolve your issue?

**Comment by roryodonnell** [comment]
I'm not sure - didn't dig into it too much. It could have been a temporary connection issue with cos - but as you say - the main point is to direct you to the unhandled NPE exception

**Comment by smcgrath-IBM** [comment]
ok, we have an internal Jira raised - CSAFE-38356. I'll keep this github issue open too. thanks

**Comment by roryodonnell** [comment]
....happy Friday!!

**Comment by bh0241** [comment]
Hi @roryodonnell this issue has been resolved in the latest public release of the Java SDK. Version 2.1.3.

Please let us know if you have any further issues with this.

**Comment by barry-hueston-IBM** [comment]
Hi @roryodonnell this issue has been resolved in the latest public release of the Java SDK. Version 2.1.3.

Please let us know if you have any further issues with this.
