### ISSUE TITLE
 java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by BhuvanaAdhi** [IBM/ibm-cos-sdk-java#18]
Hi, I am trying to connect to IBM Cloud Object Storage using domino java agents. Receiving the below error on initializing the ClientConfiguration. Same code with all the dependent jars runs on eclipse interface.

Exception in thread "AgentThread: JavaAgent" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135)
	at com.ibm.cloud.objectstorage.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:142)
	at com.ibm.cloud.objectstorage.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:137)
	at com.ibm.cloud.objectstorage.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:100)
	at com.ibm.cloud.objectstorage.ClientConfiguration.<clinit>(ClientConfiguration.java:66)
	at JavaAgent.createClient(JavaAgent.java:61)
	at JavaAgent.NotesMain(JavaAgent.java:42)
	at lotus.domino.AgentBase.runNotes(Unknown Source)
	at lotus.domino.NotesThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException
	at com.ibm.cloud.objectstorage.internal.config.InternalConfig.loadfrom(InternalConfig.java:235)
	at com.ibm.cloud.objectstorage.internal.config.InternalConfig.load(InternalConfig.java:249)
	at com.ibm.cloud.objectstorage.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:304)
	... 8 more

**Comment by smcgrath-IBM** [comment]
Hi @BhuvanaAdhi can you provide an example of your code, removing any credentials?

**Comment by BhuvanaAdhi** [comment]
import java.util.List;

import com.ibm.cloud.objectstorage.ClientConfiguration;
import com.ibm.cloud.objectstorage.SDKGlobalConfiguration;
import com.ibm.cloud.objectstorage.SdkClientException;
import com.ibm.cloud.objectstorage.auth.AWSCredentials;
import com.ibm.cloud.objectstorage.auth.AWSStaticCredentialsProvider;
import com.ibm.cloud.objectstorage.client.builder.AwsClientBuilder.EndpointConfiguration;
import com.ibm.cloud.objectstorage.oauth.BasicIBMOAuthCredentials;
import com.ibm.cloud.objectstorage.services.s3.AmazonS3;
import com.ibm.cloud.objectstorage.services.s3.AmazonS3ClientBuilder;
import com.ibm.cloud.objectstorage.services.s3.model.Bucket;
import com.ibm.cloud.objectstorage.services.s3.model.ListObjectsRequest;
import com.ibm.cloud.objectstorage.services.s3.model.ObjectListing;
import com.ibm.cloud.objectstorage.services.s3.model.S3ObjectSummary;
import com.ibm.cloud.objectstorage.ApacheHttpClientConfig;

import lotus.domino.*;

public class JavaAgent extends AgentBase {

    public void NotesMain() {

      try {
          Session session = getSession();
          AgentContext agentContext = session.getAgentContext();
          
          SDKGlobalConfiguration.IAM_ENDPOINT = "https://iam.cloud.ibm.com/identity/token";

          String bucketName = "xxxxx";  
        
          String api_key = "xxxx";
          String service_instance_id = "xxxxx"; //
          String endpoint_url = "zxxx"; 
         
          String location = "xxx"; 

        
          AmazonS3 _cosClient = createClient(api_key, service_instance_id, endpoint_url, location);

   
          
                 
          
          
      } catch(Exception e) {
          e.printStackTrace();
       }
   }
    public static AmazonS3 createClient(String api_key, String service_instance_id, String endpoint_url, String location)
    {
        AWSCredentials credentials;
        credentials = new BasicIBMOAuthCredentials(api_key, service_instance_id);
        ClientConfiguration clientConfig = null;
        try{
        	  clientConfig = new ClientConfiguration();
        	  clientConfig.withRequestTimeout(5000);
             clientConfig.setUseTcpKeepAlive(true);
             Boolean accessEnabled = new Boolean(true);
             
             AmazonS3 cosClient = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(credentials))
                     .withEndpointConfiguration(new EndpointConfiguration(endpoint_url, location)).withPathStyleAccessEnabled(accessEnabled)
                     .withClientConfiguration(clientConfig).build();
                     return cosClient;
        }catch(Exception e){
        	System.out.println(e.getCause());
        	System.out.println(e.getStackTrace());
        	  return null;
        }
       
        
       
       
    } 
   

}

**Comment by BhuvanaAdhi** [comment]
Actually, I am trying to connect to IBM Cloud from lotus notes database using java agents (In domino). I am loading the jars directly in the agent in archive folder.

**Comment by smcgrath-IBM** [comment]
@BhuvanaAdhi if the code works fine on your Eclipse IDE, but not on notes, it is likely a class loading issue. What java version & vendor are you running on your environment?

**Comment by barry-hueston-IBM** [comment]
@BhuvanaAdhi, can we close this issue, please?
