### ISSUE TITLE
Question - Async programming with java sdk

### ISSUE THREAD

**Issue by mariobriggs** [IBM/ibm-cos-sdk-java#19]
Hi,

Does the library support async put operations like the 2nd example in this AWS link

https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html

thanks in advance

**Comment by smcgrath-IBM** [comment]
Hi @mariobriggs we currently do not support async requests on the s3 Client. But the TransferManager has that ability, like below;

`TransferManager transferManager = TransferManagerBuilder.standard().withS3Client(CLIENT).build(); 
Upload upload = transferManager.upload(putRequest);
upload.waitForUploadResult();`

**Comment by mariobriggs** [comment]
@smcgrath-IBM thanks. It works great 👍

**Comment by smcgrath-IBM** [comment]
Thats good. I'll close off the issue
