### ISSUE TITLE
Is there Retry-Logic in the SDK

### ISSUE THREAD

**Issue by fishyjerky** [IBM/ibm-cos-sdk-java#2]
Hi, I'm migrating from object store and had some questions about retry-logic.  I encountered a lot of timeouts when using object store (socket and connection) and had some retry-logic built into my http-handlers. 

Does the java-sdk handle failures and retries for me?  Or should I implement my own set of retries?

Thanks.

**Comment by smcgrath-IBM** [comment]
Hi @fishyjerky there is a built in retry mechanism on 5xx http responses. This defaults to 4 attempts, but is configurable using ClientConfiguration().withMaxErrorRetry(). I can't advise on any network issues you are having, but if you think there is an issue with the SDK please send on some more detail & debug logs if you have them.

**Comment by fishyjerky** [comment]
That sounds great.  I will use it and after I migrate, I will let you guys know if I notice any network issues that could be from the COS service.
