### ISSUE TITLE
IBM AppScan issues in COS SDK

### ISSUE THREAD

**Issue by reedcozart** [IBM/ibm-cos-sdk-java#22]
We use IBM COS java SDK in one of our applications, and recently we ran IBM AppScan against our code base, and it looks like it is picking up several issues located in the IBM COS SDK. I have attached screenshots of several of these issues and traces here.
[CloudObjectStorage_ASOC_Screenshots.zip](https://github.com/IBM/ibm-cos-sdk-java/files/3179265/CloudObjectStorage_ASOC_Screenshots.zip)

**Comment by paul-carron** [comment]
@reedcozart we will investigatee these issues.

**Comment by barry-hueston-IBM** [comment]
Internal ref: CSAFE-55540

**Comment by runnerpaul** [comment]
@reedcozart this SDK is an AWS fork so we can't easily make changes. We can log the scan result with AWS but beyond that there's very little we can do.

**Comment by runnerpaul** [comment]
@reedcozart would it be possible to run that scan against the AWS sdk? I'll then use those results to open an issue with AWS.

**Comment by runnerpaul** [comment]
#close
