### ISSUE TITLE
Link in README for Code Examples is broken

### ISSUE THREAD

**Issue by cloudpitchford** [IBM/ibm-cos-sdk-java#23]
Chris.Pitchford@ibm.com here. I found this: * [Code Examples](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-using-java#examples)

Where the link: https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-using-java#examples 

should be: https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-java#java-examples

from the page at:

https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-java

**Comment by barry-hueston-IBM** [comment]
Internal Reference: CSAFE-56603

**Comment by cloudpitchford** [comment]
Thanks!
 
Chris Pitchford (Contractor)
E-mail: chris.pitchford@ibm.com
Mobile: 303.726.0787
 
 
----- Original message -----From: barry-hueston-IBM <notifications@github.com>To: IBM/ibm-cos-sdk-java <ibm-cos-sdk-java@noreply.github.com>Cc: "Chris Pitchford (Public)" <chris.pitchford@ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [IBM/ibm-cos-sdk-java] Link in README for Code Examples is broken (#23)Date: Fri, Jun 14, 2019 4:22 AM 
Internal Reference: CSAFE-56603

**Comment by smcgrath-IBM** [comment]
Hi @cloudpitchford this link was fixed in the 2.5.0 release. Can you check latest release & close this issue if all ok?

**Comment by cloudpitchford** [comment]
Thanks! I just checked.
