### ISSUE TITLE
Add Non-blocking support Java SDK

### ISSUE THREAD

**Issue by FcoJavierSainz** [IBM/ibm-cos-sdk-java#27]
Have a reactive-streams compatible interface (non-blocking) similar to AWS https://aws.amazon.com/es/blogs/developer/aws-sdk-for-java-2-x-released/

**Comment by rtveitch** [comment]
The v2 AWS Java SDK is on our radar as a potential future project, but we do not have any current plans for it at this time. Will mark as closed for now and revisit if the situation changes.

**Comment by FcoJavierSainz** [comment]
I was playing with AWS SDK but IBM COS does not support uploads without the file size, which when you streaming the file is not easy to get the final size

**Comment by FcoJavierSainz** [comment]
Hi, any news?

**Comment by rtveitch** [comment]
None yet, v2 sdk is in our backlog to investigate, but no specific plans at the moment.
