### ISSUE TITLE
InvalidLocationConstraint error while creating a bucket with encryption

### ISSUE THREAD

**Issue by balajikadambi** [IBM/ibm-cos-sdk-java#31]
Hi, I was using the Java COS SDK to create a bucket with encryption. I get the following error:
Creating new encrypted bucket: my-bucket
com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: Container storage location with specified provisioning code not available (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: ce462457-1e9a-4e10-b8a1-e0fb9c40240c), S3 Extended Request ID: null
SDK Error: Container storage location with specified provisioning code not available (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: ce462457-1e9a-4e10-b8a1-e0fb9c40240c)

I used the below configuration:
private static String COS_KP_ALGORITHM = "AES256";
	private static String COS_KP_ROOTKEY_CRN = "crn:v1:bluemix:public:kms:au-syd:a/96a264xxxx6ef14f53a6:99e18b68-7c94-4745xxxxx8337dd5a::";
	private static String COS_ENDPOINT = "https://s3.dal.cloud-object-storage.appdomain.cloud"; 
	private static String COS_API_KEY_ID = "xxxxOGdWN"; // eg "0viPHOY7LbLNa9eLftrtHPpTjoGv6hbLD1QalRXikliJ"
	private static String COS_AUTH_ENDPOINT = "https://iam.cloud.ibm.com/identity/token";
	private static String COS_SERVICE_CRN = "crn:v1:bluemix:public:cloud-object-storage:global:a/96a26456xxxxx6ef14f53a6:6a5c818e-72be-4ce2xxxxxa329d8::"; 
	private static String COS_BUCKET_LOCATION = "au-syd-smart"; // eg "us"

**Comment by typeness** [comment]
@balajikadambi I am encountering the same issue. What did you change the URL for?

**Comment by balajikadambi** [comment]
@typeness I had the endpoint URL for us-south wrong, and got the error. I used the endpoint URLs mentioned here and it worked - https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-endpoints.

**Comment by balajikadambi** [comment]
@typeness au-syd region still gives the same error for me. The endpoint is correct but still get InvalidLocationConstraint error. Have raised an issue with IBM Cloud support. 

For us-south, the code works fine.

**Comment by typeness** [comment]
@balajikadambi what helped me is setting the region not only for S3 client creation but also for bucket creation, see https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-java#java-examples-storage-class

**Comment by komrabethsalo** [comment]
I found that you need to append the service class to the region, for example `us-east-standard`; exactly as @balajikadambi balajikadambi has done above with `au-syd-smart`.
