### ISSUE TITLE
IBM COS SDK Java Examples are not working provide a 400 Invalid Argument Error

### ISSUE THREAD

**Issue by muhammadsalah** [IBM/ibm-cos-sdk-java#39]
Please refer to the following two gists I have created based on the referenced Java Code Examples.

https://gist.github.com/muhammadsalah/fc0a510ea8aa86c5a4f5b390c0394be6

https://gist.github.com/muhammadsalah/e3b3e21212b0e551e1f662f911ef1fd4

Whenever I execute the test, provided I have inserted the proper credentials, and I can inspect my token in the debugger.

I am using IBMOAuthCredentialsProvider, and it provides a token, I verified I have the correct IAM roles on IBM Cloud for my API KEY.

yet, I fail to list the buckets in the service.

I am receiving the following error:

Error Code: 400

Error Message: Invalid Argument

Error XML:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>InvalidArgument</Code><Message>Invalid Argument</Message><RequestId>4d6372ff-4afc-4103-8c4e-a6d4255f62ad</RequestId><httpStatusCode>400</httpStatusCode></Error>

Which is an AmazonS3Exception

I have tried the 2.10.0 version and the 2.8.0 version from the maven central.

I am only following the code examples on this:

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-java

Thank you.

**Comment by nglange** [comment]
Thanks for raising this issue - I'll verify and update the documentation. Did you end up altering it and getting it to work?

**Comment by muhammadsalah** [comment]
@nglange I could not get around it, and I think my viable alternative is to use the REST directly.

**Comment by nglange** [comment]
I don't suppose you'd be able to capture the outgoing request via Wireshark or other similar tool?  I feel like something in the request is getting mangled in the model import but I can't be sure.

**Comment by muhammadsalah** [comment]
@nglange I will capture the data for you via Wireshark, and report back

**Comment by muhammadsalah** [comment]
@nglange I have captured the packets using wireshark.
I also filtered them according to the IP which resolved with the Bucket Endpoint.
I ran the code twice, same result in the flight record.
Can you advise a way for me to send you the packet trace?
I can not share this on the tracker, thank you.

**Comment by nglange** [comment]
For sure - you can contact me by email: `nicholas.lange[at]ibm.com`.

**Comment by muhammadsalah** [comment]
@nglange I have sent you via email the packets.

**Comment by avinash1IBM** [comment]
@muhammadsalah could you please check with the latest version and if resolved, please close this issue

**Comment by IBMalok** [comment]
Closing since the fix was already provided.

**Comment by IBMalok** [comment]
Closing since the fix was already provided.
