### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by YiannisGkoufas** [IBM/ibm-cos-sdk-java#4]
We cannot use this library in Android and I couldn't find any guides to use Object Storage in Android besides this deprecated library.
Can you let us know what are the steps needed to modify this library to use it Android?
Or any potential workaround to access Object Storage in Android?

Thanks!

**Comment by smcgrath-IBM** [comment]
Hi @YiannisGkoufas Android is not supported in the java sdk. At this point I don't have a timeline of when an Android sdk will be available.

**Comment by smcgrath-IBM** [comment]
HI @YiannisGkoufas take a look at the documentation around hmac headers;
https://console.bluemix.net/docs/services/cloud-object-storage/hmac/credentials.html#using-hmac-credentials

https://console.bluemix.net/docs/services/cloud-object-storage/hmac/hmac-signature.html#constructing-an-hmac-signature

If you are using IAM credentials you will not be able to create the required headers though.

**Comment by YiannisGkoufas** [comment]
Hi @smcgrath-IBM  please have a look in this branch: https://github.com/YiannisGkoufas/ibm-cos-sdk-java/tree/android 
`mvn clean install`
and then in the gradle file just import:
`compile group: "com.ibm.cos", name:"ibm-cos-java-sdk-s3", version:'2.0.1-SNAPSHOT'`
So far all the java examples seem to be working
