### ISSUE TITLE
SAST : Validation.Required

### ISSUE THREAD

**Issue by JyothiBacham** [IBM/ibm-cos-sdk-java#41]
Validation.Required : 

Source: _com.ibm.cloud.objectstorage.ImmutableRequest.getParameters():Map via AmazonHttpClient:1058_ 
Sink: _com.ibm.cloud.objectstorage.Request.setParameters(Map):void via AmazonHttpClient:1099_

**Comment by JyothiBacham** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/43532217/121842963-f939b400-ccfe-11eb-92a4-55b14129e47c.png">

**Comment by JyothiBacham** [comment]
Hi, our SAST(AppScan) reports this vulnerability from COS jar.. can you please check if this is a valid issue and needs any change..

**Comment by IBMeric** [comment]
This code is related to upstream metrics collection that COS does not support.
