### ISSUE TITLE
SAST : Privacy.DataLeakage

### ISSUE THREAD

**Issue by JyothiBacham** [IBM/ibm-cos-sdk-java#42]
Privacy.DataLeakage : 

Source: _org.apache.http.HttpEntity.getContent():InputStream via CRC32ChecksumResponseInterceptor:78_

Sink: _org.apache.http.protocol.HttpContext.setAttribute(String;Object):void via CRC32ChecksumResponseInterceptor:77_

**Comment by JyothiBacham** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/43532217/121843275-8e3cad00-ccff-11eb-88f3-6f1593bf255d.png">

**Comment by JyothiBacham** [comment]
Hi, our SAST(AppScan) reports this vulnerability from COS jar.. can you please check if this is a valid issue and needs any change..

**Comment by JyothiBacham** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/43532217/121843342-add3d580-ccff-11eb-9ac6-2557991170a3.png">

**Comment by JyothiBacham** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/43532217/121843379-bdebb500-ccff-11eb-8ef6-7258ac87462e.png">

**Comment by IBMeric** [comment]
This code applies only to the upstream JSON protocol that COS does not support: https://github.com/IBM/ibm-cos-sdk-java/blob/e74a8c118b66299ecdae96ae0174030435d9713f/ibm-cos-java-sdk-core/src/main/java/com/ibm/cloud/objectstorage/http/apache/client/impl/CRC32ChecksumResponseInterceptor.java#L39.
