### ISSUE TITLE
SAST : Communications.SSL

### ISSUE THREAD

**Issue by JyothiBacham** [IBM/ibm-cos-sdk-java#43]
Communications.SSL : 
<img width="616" alt="image" src="https://user-images.githubusercontent.com/43532217/121843485-effd1700-ccff-11eb-8b58-fd06395a1779.png">

**Comment by JyothiBacham** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/43532217/121843530-0f943f80-cd00-11eb-837c-1e83409cb34b.png">
<img width="604" alt="image" src="https://user-images.githubusercontent.com/43532217/121843545-18851100-cd00-11eb-9936-93654eac1038.png">

**Comment by IBMeric** [comment]
The storage service and authentication servers are responsible for authenticating clients. The SDK helps clients write applications to talk to those services. Connections to the public cloud server uses CA certificates.
