### ISSUE TITLE
"mvn clean install" failed

### ISSUE THREAD

**Issue by lee-zhg** [IBM/ibm-cos-sdk-java#45]
when execute "mvn clean install" command, it failed with the messages below. What do option 6 and 7 refer? Thank you

[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ibm-cos-java-sdk-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ ibm-cos-java-sdk-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 571 source files to /Users/leezhang/root/Lee/Project/Garage/2021/CVS Health - Commercial Claims/git/lee/ibm-cos-sdk-java/ibm-cos-java-sdk-core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: Source option 6 is no longer supported. Use 7 or later.
[ERROR] error: Target option 6 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for IBM COS SDK for Java 2.11.0:
[INFO] 
[INFO] IBM COS SDK for Java ............................... SUCCESS [  0.212 s]
[INFO] IBM COS SDK for Java - Core ........................ FAILURE [  1.504 s]
[INFO] IBM COS SDK for Java - Test Utils .................. SKIPPED
[INFO] IBM COS Java SDK for COS KMS ....................... SKIPPED
[INFO] IBM COS Java SDK for Amazon S3 ..................... SKIPPED
[INFO] IBM COS SDK For Java ............................... SKIPPED
[INFO] IBM COS SDK for Java - BOM ......................... SKIPPED
[INFO] IBM COS SDK for Java - Bundle ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.833 s
[INFO] Finished at: 2021-12-07T09:46:00-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project ibm-cos-java-sdk-core: Compilation failure: Compilation failure: 
[ERROR] error: Source option 6 is no longer supported. Use 7 or later.
[ERROR] error: Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ibm-cos-java-sdk-core

**Comment by IBMeric** [comment]
Thanks for your message. I believe this is related to the JRE version. What JVM are you building for?

If you are building based on the readme, I just noticed that it is in error. Java 6 may no longer be supported because it has hit EOL. I would recommend using Java 8, which is LTS and is still being maintained.

**Comment by IBMeric** [comment]
@lee-zhg We officially dropped support for Java 6 and Java 7 in 2.11.1.
