### ISSUE TITLE
PRISMA-2021-0213 vulnerability in latest ibm-cos-java-sdk-bundle 2.11.0 jar

### ISSUE THREAD

**Issue by klajok** [IBM/ibm-cos-sdk-java#46]
The version of jackson-databind (`2.12.0`) that is shaded within the ibm-cos-java-sdk-bundle jar alerts security scanner. There is reported enigmatic "PRISMA-2021-0213" without details except that the vulnerability has been fixed in jackson-databind version `2.13.1`.

Please update shaded jackson-databind library.

See similar #38 reported in the past.

**Comment by IBMeric** [comment]
Thanks for your report. I'll get this scheduled for our upcoming maintenance release.

**Comment by tcherel** [comment]
Thanks @IBMeric 
Any ETA by any chances?

**Comment by IBMeric** [comment]
Yes @tcherel, this work is already done and has just started going through final release.  Barring any surprises, this should be available after the Monday US holiday.

**Comment by IBMeric** [comment]
@klajok @tcherel This issue has been resolved in 2.11.1. Please verify and close this ticket.

**Comment by tcherel** [comment]
Thanks @IBMeric this is very good news.
Will verify and close.

**Comment by klajok** [comment]
Many thanks. The scanner no longer reports the library after update to 2.11.1.
