### ISSUE TITLE
Example code in README.md confusing

### ISSUE THREAD

**Issue by YossiTamari** [IBM/ibm-cos-sdk-java#5]
In the example in README.md, the method listBuckets receives a s3Client parameter, but then it ignores it and uses the static member _s3Client instead.
I believe the method should use the parameter. In fact, I think the static member should be removed from the code and a simple local variable should be used in main().

**Comment by wbhuberIBM** [comment]
@YossiTamari  README updated with clarity:

https://github.com/IBM/ibm-cos-sdk-java/README.md
