### ISSUE TITLE
ibm-cos-java-sdk-bundle 2.11.1 contains vulnerable jackson-databind 2.13.1

### ISSUE THREAD

**Issue by klajok** [IBM/ibm-cos-sdk-java#52]
The library `jackson-databind` version `2.13.1` is embedded in the latest version `2.11.1` of `ibm-cos-java-sdk-bundle` .

According to https://github.com/advisories/GHSA-57j2-w4cx-62h2 the above version of Jackson Databind is vulnerable.

Please prepare new release of COS Java SDK bundle with updated Jackson Databind library.

**Comment by IBMeric** [comment]
Thanks for your report. We have an internal ticket to complete this work.

**Comment by hbornstein747** [comment]
Do you have an ETA when the new version will be available?

**Comment by hbornstein747** [comment]
Latest CVE requires update to 2.13.2.2.  Hopefully this will be included. (I am with the the CP4D dev team)

**Comment by avinash1IBM** [comment]
Thank for the update. This change will be included in the next release. Thanks

**Comment by avinash1IBM** [comment]
Hello, 
The next release will be in second quarter. 
Thanks.

**Comment by IBMeric** [comment]
@klajok @hbornstein747 We have released 2.11.2 to address this issue. Please verify and close this ticket.

**Comment by hbornstein747** [comment]
Thank you.  I can verify the issue is resolved.

**Comment by klajok** [comment]
Thank you.
