### ISSUE TITLE
Report security vulnerabilities found via HCL AppScan.

### ISSUE THREAD

**Issue by sann-jay** [IBM/ibm-cos-sdk-java#53]
Hi Team,

I work for an IBM product and we bundle our application with various IBM Cloud jars. I just wanted to know how we could report some security vulnerabilities found via HCL AppScan in various IBM Cloud JAR files that we bundle in our application.

I can share the reports internally, if needed.

Thanks!

<img width="868" alt="image" src="https://user-images.githubusercontent.com/2337153/174328084-d3465150-55a9-4537-b62b-aa4b91156bdf.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/2337153/174328487-a2b53e7f-bc95-4c84-bd12-19bb65521725.png">
<img width="895" alt="image" src="https://user-images.githubusercontent.com/2337153/174328804-7fe6a84b-60d1-48cc-843e-8597fa47da16.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/2337153/174328965-cc585887-d71b-43c6-ba05-2b26bdfd93c2.png">

**Comment by IBMalok** [comment]
Thanks for your report. Someone is looking at this now and opened an internal ticket.

**Comment by arnabm28** [comment]
hi @sann-jay 

With respect to the above App scan issues, we have concluded all of the vulnerabilities found and explanation to  all of the above was provided.
The same was concluded via email.
May I request you to please close this Github issue.

Thanks.
