### ISSUE TITLE
PRISMA-2023-0067: jackson-core package versions before 2.15.0 are vulnerable to Denial of Service (DoS)

### ISSUE THREAD

**Issue by tcherel** [IBM/ibm-cos-sdk-java#58]
See https://github.com/FasterXML/jackson-core/pull/827

Can we get a rough estimate as when this upgrade might be done/available?

Thanks.

**Comment by avinash1IBM** [comment]
Thanks for reporting the issue. I will work with our team and will update you with the rough estimate at the earliest. Thanks

**Comment by avinash1IBM** [comment]
@tcherel We looked in the the vulnerability details that you shared, and found that the mentioned vulnerable function is not used at all in this java-sdk. So we will upgrade this dependency version and will include it the next release.

**Comment by tcherel** [comment]
Thanks @avinash1IBM 
Good to hear that it is not vulnerable but good to hear that you will upgrade anyway (some of our customers are pushing back as long as vulnerability is there).
Do you have a rough ETA for the next release?

**Comment by tcherel** [comment]
Thanks @avinash1IBM 
Closing.
