### ISSUE TITLE
Black Duck was detected it as Vulnerability

### ISSUE THREAD

**Issue by 232608** [IBM/ibm-cos-sdk-java#60]
![image](https://github.com/IBM/ibm-cos-sdk-java/assets/108425098/05e8b61a-f7de-451f-86da-6f80297da93f)
![image](https://github.com/IBM/ibm-cos-sdk-java/assets/108425098/fcccadbc-ffd6-4fd5-9b03-8965e217197e)

**Comment by IBMalok** [comment]
The vulnerability was reported for IBM WebSphere and had nothing to do with IBM-COS-SDK, hence it is a false positive. Because of the word "sdk," I was reported.
