### ISSUE TITLE
compatibility with jakarta

### ISSUE THREAD

**Issue by carminedigre** [IBM/ibm-cos-sdk-java#67]
is this library compatible for Jakarta EE?

**Comment by IBMalok** [comment]
@carminedigre  - Did you try, and it didn't work?

**Comment by carminedigre** [comment]
<img width="647" alt="Screenshot 2024-02-27 at 09 53 08" src="https://github.com/IBM/ibm-cos-sdk-java/assets/89909047/053660c4-d240-4680-b076-ee0f678aefdb">

the current latest (2.13.4) version has still javax.

**Comment by IBMalok** [comment]
Currently, no fix is needed. Thus, closing the ticket.
