### ISSUE TITLE
Example code to get endpoint_url from endpoints

### ISSUE THREAD

**Issue by rvennam** [IBM/ibm-cos-sdk-java#7]
The generated credentials on IBM Cloud are in this format
```
{
    "apikey": "xxxxxxx",
    "endpoints": "https://cos-service.bluemix.net/endpoints",
    "iam_apikey_description": "xxxxxxx",
    "iam_apikey_name": "xxxxxxx",
    "iam_role_crn": "xxxxxxx",
    "iam_serviceid_crn": "xxxxxxx",
    "resource_instance_id": "xxxxxxx"
  }
```
The example code should show how to get the correct region endpoint url from IBM Cloud credentials -> endpoints 

        String endpoint_url = "https://s3-api.us-geo.objectstorage.softlayer.net";
        String location = "us";

**Comment by Patrick-Browne** [comment]
@rvennam thanks we'll take a look into this and get the example code updated.

**Comment by nglange** [comment]
This was updated [here](https://console.bluemix.net/docs/services/cloud-object-storage/libraries/java.html#code-examples) a while ago, can this be closed?  😬

**Comment by hegdehr** [comment]
@rvennam Can we close this ticket please? Thanks!
